# Generated by Django 6.0.1 on 2026-01-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_shoppinglistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
