# Generated by Django 6.0.1 on 2026-01-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_alter_shoppinglistitem_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(choices=[('unit', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro')], default='unit', max_length=5),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
